---
name: Authen-Simple-DBI
version: 0.1
author:
  - 'Christian Hansen C<ch@ngmedia.com>'
abstract: Simple DBI authentication
license: perl
requires:
  Authen::Simple: 0.3
  DBI: 0
provides:
  Authen::Simple::DBI:
    file: lib/Authen/Simple/DBI.pm
    version: 0.1
generated_by: Module::Build version 0.2611
